version: '3.8'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - "29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
          - 8090:8080
      depends_on:
        - kafka
        - zookeeper
      environment:
          DYNAMIC_CONFIG_ENABLED: true
          KAFKA_CLUSTERS_0_NAME: test-cluster
          KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092, PLAINTEXT_HOST://localhost:9092'
          KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"
          KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      # volumes:
      #   - ./config:/etc/kafkaui/dynamic_config.yaml
